# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rspec.info/documentation/ for more information about RSpec

require 'webmock/rspec'

RSpec.configure do |config|
  # Enable flags like --only-failures and --next-failure
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Disable RSpec exposing methods globally on `Module` and `main`
  config.disable_monkey_patching!

  config.expect_with :rspec do |c|
    c.syntax = :expect
  end

  ENV["PEAR_PROGRAMMER_ENV"] = "development"

  config.before(:each) do
    stub_request(:any, /localhost/)
      .to_return { |_request|
        {status: 200, body: {response: 'stubbed response'}.to_json, headers: {'Content-Type' => 'application/json'}}
      }
    allow(PairProgrammer::Configuration).to receive(:api_key).and_return('fake_api_key')
  end
end
